### PR TITLE
Fix for #118

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
@bburan can you confirm it fixes your issue (and with enaml too)

### CODE REVIEW

**Comment by bburan** [comment]
I get the following:

```
(psi-nafc) c:\Users\lbhb\projects\psi-nafc\src\psilbhb>enaml-run test.enaml
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\lbhb\anaconda3\envs\psi-nafc\Scripts\enaml-run.exe\__main__.py", line 7, in <module>
  File "c:\Users\lbhb\anaconda3\envs\psi-nafc\Lib\site-packages\enaml\runner.py", line 44, in main
    code = EnamlCompiler.compile(ast, enaml_file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lbhb\anaconda3\envs\psi-nafc\Lib\site-packages\enaml\core\enaml_compiler.py", line 179, in compile
    return compiler.visit(node)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lbhb\anaconda3\envs\psi-nafc\Lib\site-packages\enaml\core\enaml_ast.py", line 418, in visit
    result = visitor(node, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lbhb\anaconda3\envs\psi-nafc\Lib\site-packages\enaml\core\enaml_compiler.py", line 207, in visit_Module
    return cg.to_code()
           ^^^^^^^^^^^^
  File "c:\Users\lbhb\anaconda3\envs\psi-nafc\Lib\site-packages\enaml\core\code_generator.py", line 118, in to_code
    return bc_code.to_code()
           ^^^^^^^^^^^^^^^^^
  File "c:\Users\lbhb\anaconda3\envs\psi-nafc\Lib\site-packages\bytecode\bytecode.py", line 305, in to_code
    cfg = _bytecode.ControlFlowGraph.from_bytecode(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lbhb\anaconda3\envs\psi-nafc\Lib\site-packages\bytecode\cfg.py", line 832, in from_bytecode
    assert active_try_begin
AssertionError
```
The test file is:
```
try:
    pass
except Exception as e:
    pass
```
It can be run with `enaml-run test.enaml` (yes, it doesn't have a Main in it, but that's OK since it still triggers the error).

**Comment by MatthieuDartiailh** [comment]
If you can it would be great yes. It seems your real issue is not related to dead code only and I would like to understand it better.

**Comment by MatthieuDartiailh** [comment]
ping @bburan

**Comment by bburan** [comment]
I was trying to find the original code that triggered this, but since I did not need the "as" part of the exception, which is what was triggering this error, I had already removed it to work around this issue. However, the general gist is this:
```
import logging
log = logging.getLogger(__name__)
try:
    import backend_1
    backend_1_available = True
except ImportError as e:
    log.exception(e)
    backend_1_available = False
```
It's useful to capture and log the error message (since there are different reasons one may get an ImportError). This was at the top of my enaml file and was failing. The dead code example I gave you was a minimal working example, but this particular example is something you might expect to encounter in the real world. You may want to modify the behavior or layout of an Enaml widget/application based on whether backend_1_available is True or False. Now, we could definitely put this in a Python file and import the variable from the file; however, the whole point of Enaml is that any Python code should be valid, so users would end up getting a confusing error message if they do a "try/except ... as e" in their Enaml file.

**Comment by MatthieuDartiailh** [comment]
Thanks for the actual use case. This is not only dead code so I definitively need to fix bytecode to support it.

**Comment by MatthieuDartiailh** [comment]
So from the actual use case I was able to confirm that the issue does not stem from bytecode. The enaml compiler is doing something invalid and it needs to be fixed. This PR could nonethless be valuable so I will merge it and keep working on the enaml side.

**Pull request merged**
